import * as stylex from "@stylexjs/stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });

export const styles = stylex.create({
  root: {
    position: "relative",
    display: "flex",
    width: "100%",
    minHeight: "9rem",
    flexDirection: "column",
    justifyContent: "space-between",
    containerType: "inline-size",
    padding: "0.25rem",
    borderWidth: "1px",
    borderColor: "var(--border-color-container)",
    borderRadius: "var(--radius-sm)",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, translate, scale, rotate, filter, backdrop-filter, display, content-visibility, overlay, pointer-events",
    transitionTimingFunction: "var(--default-transition-timing-function)",
    transitionDuration: "var(--default-transition-duration)",
    boxShadow: { default: null, ":focus-within": "0 0 0 3px var(--primary)" },
  },
  cancelPosition: { position: "absolute", top: "-0.75rem", right: "-0.5rem" },
  cancelButton: {
    padding: "0.25rem",
    borderRadius: "3.40282e38px",
    backgroundColor: {
      default: "var(--color-zinc-200)",
      "@media (prefers-color-scheme: dark)": "var(--color-zinc-800)",
    },
    scale: {
      default: null,
      "@media (hover: hover)": { ":hover": 1.05 },
      ":active": 0.95,
    },
  },
  cancelIcon: { width: "0.75rem", height: "0.75rem" },
  visuallyHidden: {
    position: "absolute",
    width: "1px",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
  textarea: {
    fieldSizing: "content",
    width: "100%",
    minHeight: "4.5rem",
    flex: 1,
    resize: "none",
    paddingInline: "0.25rem",
    paddingBlock: "0.125rem",
    outline: "none",
    backgroundColor: "transparent",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--text-sm-line-height)",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.5rem",
    paddingInline: "0.25rem",
    color: "var(--color-comment)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--text-sm-line-height)",
  },
  footerHint: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    color: "color-mix(in oklab, var(--color-comment) 90%, transparent)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--text-xs-line-height)",
  },
  markdownHint: {
    display: { default: "flex", "@container (max-width: 17.999rem)": "none" },
    alignItems: "center",
    gap: "0.5rem",
  },
  actions: { display: "flex", alignItems: "center", gap: "0.5rem" },
  submit: {
    display: "flex",
    alignItems: "center",
    gap: "0.125rem",
    scale: {
      default: null,
      "@media (hover: hover)": { ":hover": 1.05 },
      ":active": 0.95,
    },
    opacity: { default: 1, ":disabled": 0.5 },
  },
  actionIcon: { width: "1rem", height: "1rem" },
  loadingIcon: {
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  anonymous: { display: "flex", alignItems: "center", gap: "0.25rem" },
});
