export const viewports = {
  desktop: { width: 1440, height: 1000 },
  mobile: { width: 390, height: 844 },
};

export const colorSchemes = ["light", "dark"];

export const appPages = [
  { id: "home", path: "/" },
  { id: "post-list-1", path: "/post" },
  { id: "post-list-2", path: "/post/2" },
  { id: "tag-stylex", path: "/tags/StyleX" },
  {
    id: "tag-pagination-1",
    path: "/tags/%E8%A7%86%E8%A7%89%E5%9B%9E%E5%BD%92",
  },
  {
    id: "tag-pagination-2",
    path: "/tags/%E8%A7%86%E8%A7%89%E5%9B%9E%E5%BD%92/2",
  },
  { id: "archive", path: "/archive" },
  { id: "about", path: "/about", action: "wait-comments" },
  { id: "credits", path: "/credits" },
  { id: "fixture-page", path: "/fixture-page" },
  { id: "article", path: "/post/stylex-migration", action: "wait-comments" },
  { id: "not-found", path: "/404", expectedStatus: 404 },
  { id: "notification-missing-query", path: "/account/notification" },
  {
    id: "notification-ready",
    path: "/account/notification?email=reader%40example.com&signature=fixture&expiresAtTimestampSec=2147483647",
  },
];

// Locators intentionally use stable HTML semantics, visible copy and IDs. They do
// not depend on Tailwind class names, which disappear during the migration.
export const componentShots = [
  { id: "navbar", path: "/", locator: "header" },
  {
    id: "home-hero-section",
    path: "/",
    locator: "section",
    hasText: "Yunfi",
    nth: 0,
  },
  { id: "home-statistics", path: "/", locator: "section", hasText: "字数" },
  { id: "footer", path: "/", locator: "a[href='/feed.xml']", ancestor: 3 },
  {
    id: "list-hero",
    path: "/post",
    locator: "section",
    hasText: "文章列表",
    nth: 0,
  },
  {
    id: "post-list-item",
    path: "/post",
    locator: "a[href='/post/stylex-migration']",
    ancestor: 2,
  },
  {
    id: "post-time",
    path: "/post",
    locator: "a[href='/post/stylex-migration'] + div",
  },
  {
    id: "post-tags",
    path: "/post",
    locator: "a[href='/tags/StyleX']",
    ancestor: 2,
  },
  {
    id: "pagination",
    path: "/post",
    locator: "a[href='/post/2']",
    ancestor: 2,
  },
  {
    id: "article-hero",
    path: "/post/stylex-migration",
    locator: "section",
    hasText: "从 Tailwind CSS 迁移到 StyleX 的完整记录",
    nth: 0,
  },
  {
    id: "series-card",
    path: "/post/stylex-migration",
    locator: "section",
    hasText: "系列文章",
    nth: 0,
  },
  {
    id: "article-content",
    path: "/post/stylex-migration",
    locator: "#article-content",
  },
  {
    id: "github-card",
    path: "/post/stylex-migration",
    locator: "[data-article-embedded-element='github-repo']",
  },
  {
    id: "copy-button",
    path: "/post/stylex-migration",
    locator: "#article-content pre",
    nth: 0,
  },
  {
    id: "github-card-loading",
    path: "/post/stylex-migration?ghFixture=loading",
    locator: "[data-article-embedded-element='github-repo']",
    action: "github-loading",
  },
  {
    id: "github-card-rate-limit",
    path: "/post/stylex-migration?ghFixture=rate-limit",
    locator: "[data-article-embedded-element='github-repo']",
    action: "github-rate-limit",
  },
  {
    id: "github-card-error",
    path: "/post/stylex-migration?ghFixture=error",
    locator: "[data-article-embedded-element='github-repo']",
    action: "github-error",
  },
  {
    id: "copy-button-success",
    path: "/post/stylex-migration",
    locator: "#article-content pre",
    nth: 0,
    action: "copy-code-success",
  },
  {
    id: "copy-button-error",
    path: "/post/stylex-migration",
    locator: "#article-content pre",
    nth: 0,
    action: "copy-code-error",
  },
  {
    id: "toc",
    path: "/post/stylex-migration",
    locator: "text=文章目录",
    ancestor: 1,
    viewport: "desktop",
  },
  {
    id: "copyright-card",
    path: "/post/stylex-migration",
    locator: "section",
    hasText: "CC BY-NC-SA 4.0",
  },
  {
    id: "similar-posts",
    path: "/post/stylex-migration",
    locator: "h2",
    hasText: "相关推荐",
    ancestor: 2,
  },
  {
    id: "prev-next",
    path: "/post/stylex-migration",
    locator: "p",
    hasText: "下一篇",
    ancestor: 3,
  },
  {
    id: "comment-shell",
    path: "/post/stylex-migration",
    locator: "section",
    hasText: "评论",
    nth: 0,
    action: "wait-comments",
  },
  {
    id: "notification",
    path: "/account/notification",
    locator: "main, body",
    nth: 0,
  },
  {
    id: "date-popover",
    path: "/post/stylex-migration",
    locator: "[data-slot='popover-popup']",
    action: "date-popover",
  },
  {
    id: "mobile-scrolled-navbar",
    path: "/post/stylex-migration",
    locator: "header",
    viewport: "mobile",
    action: "scroll-article",
  },
  {
    id: "mobile-nav-drawer",
    path: "/post/stylex-migration",
    locator: "[data-vaul-drawer]",
    viewport: "mobile",
    action: "open-drawer",
  },
  {
    id: "mobile-toc-popover",
    path: "/post/stylex-migration",
    locator: "[data-slot='popover-popup']",
    viewport: "mobile",
    action: "open-toc",
  },
  {
    id: "comment-visitor-login",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "text=使用社交账号登录",
    ancestor: 2,
    action: "wait-comments",
  },
  {
    id: "comment-visitor-editor",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "textarea",
    ancestor: 2,
    action: "comment-visitor",
  },
  {
    id: "comment-dialog",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='dialog-content']",
    action: "comment-dialog",
  },
  {
    id: "comment-tabs",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='tabs']",
    action: "comment-dialog",
  },
  {
    id: "comment-input",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='input']",
    action: "comment-dialog",
  },
  {
    id: "comment-button",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='button']",
    action: "comment-dialog",
  },
  {
    id: "comment-label",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='label']",
    action: "comment-dialog",
  },
  {
    id: "comment-list",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "text=共1条留言",
    ancestor: 3,
    action: "wait-comments",
  },
  {
    id: "comment-item",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "#comment-101",
    action: "wait-comments",
  },
  {
    id: "comment-parent",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "#comment-101",
    ancestor: 1,
    action: "wait-comments",
  },
  {
    id: "comment-reactions",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "button[aria-pressed]",
    ancestor: 1,
    action: "wait-comments",
  },
  {
    id: "comment-reaction-picker",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "button[aria-label='thumbs up']",
    ancestor: 3,
    action: "comment-reaction-picker",
  },
  {
    id: "comment-dropdown",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "[data-slot='dropdown-menu-content']",
    action: "comment-dropdown",
  },
  {
    id: "comment-reply-editor",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "textarea[placeholder^='回复']",
    ancestor: 2,
    action: "comment-reply",
  },
  {
    id: "comment-auto-resize",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "textarea[placeholder^='回复']",
    ancestor: 4,
    action: "comment-reply",
  },
  {
    id: "comment-user-editor",
    path: "/post/stylex-migration?commentFixture=user",
    locator: "img[alt='Fixture User']",
    ancestor: 2,
    action: "comment-user",
  },
  {
    id: "comment-error",
    path: "/post/stylex-migration?commentFixture=error",
    locator: "button",
    hasText: "重试",
    ancestor: 1,
    action: "comment-error",
  },
  {
    id: "comment-pagination",
    path: "/post/stylex-migration?commentFixture=pagination",
    locator: "button",
    hasText: "加载更多",
    ancestor: 1,
    action: "wait-comments",
  },
  {
    id: "comment-reply-pagination",
    path: "/post/stylex-migration?commentFixture=pagination",
    locator: "button",
    hasText: "加载更多回复",
    ancestor: 2,
    action: "wait-comments",
  },
  {
    id: "comment-edit",
    path: "/post/stylex-migration?commentFixture=list",
    locator: "textarea",
    ancestor: 2,
    action: "comment-edit",
  },
  {
    id: "comment-delete-error",
    path: "/post/stylex-migration?commentFixture=delete-error",
    locator: "[data-sonner-toast]",
    action: "comment-delete",
  },
  {
    id: "comment-update-error",
    path: "/post/stylex-migration?commentFixture=update-error",
    locator: "[data-sonner-toast]",
    action: "comment-update",
  },
  {
    id: "comment-reaction-error",
    path: "/post/stylex-migration?commentFixture=reaction-error",
    locator: "[data-sonner-toast]",
    action: "comment-reaction",
  },
  {
    id: "comment-delete-success",
    path: "/post/stylex-migration?commentFixture=delete-success",
    locator: "astro-island[component-export='Comment']",
    ancestor: 1,
    action: "comment-delete",
  },
  {
    id: "comment-update-success",
    path: "/post/stylex-migration?commentFixture=update-success",
    locator: "text=Fixture edited comment",
    ancestor: 3,
    action: "comment-update",
  },
  {
    id: "comment-reaction-success",
    path: "/post/stylex-migration?commentFixture=reaction-success",
    locator: "button[aria-pressed]",
    hasText: "👎",
    ancestor: 1,
    action: "comment-reaction",
  },
  {
    id: "comment-admin-spam-badge",
    path: "/post/stylex-migration?commentFixture=admin",
    locator: "text=垃圾评论",
    ancestor: 1,
    action: "wait-comments",
  },
  {
    id: "comment-admin-menu",
    path: "/post/stylex-migration?commentFixture=admin",
    locator: "[data-slot='dropdown-menu-content']",
    action: "comment-dropdown",
  },
  {
    id: "footer-copy-success",
    path: "/",
    locator: "[data-sonner-toast]",
    action: "copy-email-success",
  },
  {
    id: "footer-copy-error",
    path: "/",
    locator: "[data-sonner-toast]",
    action: "copy-email-error",
  },
  {
    id: "subscribe-pending",
    path: "/account/notification?email=reader%40example.com&signature=fixture&expiresAtTimestampSec=2147483647&subscribeFixture=pending",
    locator: "text=取消订阅中...",
    action: "subscribe-pending",
  },
  {
    id: "subscribe-error",
    path: "/account/notification?email=reader%40example.com&signature=fixture&expiresAtTimestampSec=2147483647&subscribeFixture=error",
    locator: "text=取消订阅失败: Fixture unsubscribe error",
    action: "subscribe-click",
  },
  {
    id: "subscribe-success",
    path: "/account/notification?email=reader%40example.com&signature=fixture&expiresAtTimestampSec=2147483647&subscribeFixture=success",
    locator: "text=取消订阅成功",
    ancestor: 1,
    action: "subscribe-click",
  },
  {
    id: "resubscribe-success",
    path: "/account/notification?email=reader%40example.com&signature=fixture&expiresAtTimestampSec=2147483647&subscribeFixture=success",
    locator: "text=重新订阅成功",
    ancestor: 1,
    action: "resubscribe-click",
  },
];
