import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  popover: {
    position: "sticky",
    top: "var(--navbar-height)",
    isolation: "isolate",
    zIndex: 10,
    display: "flex",
    justifyContent: "flex-end",
  },
  trigger: {
    pointerEvents: "auto",
    display: "flex",
    width: "2.5rem",
    height: "2.5rem",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderColor: "var(--border-color-container)",
    backgroundColor: "var(--background)",
  },
  icon: { width: "1.5rem", height: "1.5rem", color: "var(--color-heading)" },
  positioner: { zIndex: 50 },
  panel: {
    pointerEvents: "auto",
    width: "19rem",
    borderWidth: "1px",
    borderColor: "var(--border-color-container)",
    backgroundColor: "var(--background)",
    paddingInline: "1.5rem",
    paddingBlock: "2rem",
    color: "var(--color-comment)",
  },
  sidebar: {
    position: "sticky",
    top: "var(--navbar-height)",
    isolation: "isolate",
    zIndex: 10,
    paddingBlock: "2rem",
  },
  sidebarPanel: {
    pointerEvents: "auto",
    width: "fit-content",
    borderTopWidth: "1px",
    borderBottomWidth: "1px",
    borderStyle: "dashed",
    borderColor: "var(--border-color-container)",
    backgroundColor: "var(--background)",
    paddingInline: "0.5rem",
    paddingTop: "1rem",
    paddingBottom: "2rem",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    color: {
      default: "color-mix(in oklab, var(--color-comment) 75%, transparent)",
      "@media (prefers-color-scheme: dark)":
        "color-mix(in oklab, var(--color-comment) 90%, transparent)",
    },
  },
  title: { marginBottom: "0.5rem", fontSize: "1.25rem", lineHeight: "1.75rem" },
  entry: {
    position: "relative",
    minWidth: 0,
    paddingBlock: "0.25rem",
    "::before": {
      position: "absolute",
      top: "50%",
      left: "-0.25rem",
      height: "1rem",
      width: "2px",
      translate: "0 -50%",
      borderRadius: "calc(var(--radius) - 2px)",
      backgroundColor: "color-mix(in oklab, var(--primary) 80%, transparent)",
      opacity: 0,
      transitionProperty: "opacity",
      transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      transitionDuration: "150ms",
      content: '""',
    },
  },
  activeEntry: { "::before": { opacity: 1 } },
  link: {
    display: "inline-block",
    width: "100%",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    verticalAlign: "middle",
    transitionProperty: "color, margin-left, transform",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
    userSelect: "none",
    color: {
      default: null,
      "@media (hover: hover)": { ":hover": "var(--color-content)" },
    },
  },
  activeLink: { color: "var(--color-heading)" },
});
