/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as Sitemap0DotxmlRouteImport } from './routes/sitemap-0[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AchieveRouteImport } from './routes/achieve'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as PageRouteImport } from './routes/$page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIndexRouteImport } from './routes/post.index'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as AccountNotificationRouteImport } from './routes/account.notification'
import { Route as TagsTagPageRouteImport } from './routes/tags.$tag.$page'
import { Route as PostSlugOgDotpngRouteImport } from './routes/post.$slug.og[.]png'

const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap0DotxmlRoute = Sitemap0DotxmlRouteImport.update({
  id: '/sitemap-0.xml',
  path: '/sitemap-0.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AchieveRoute = AchieveRouteImport.update({
  id: '/achieve',
  path: '/achieve',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationRoute = AccountNotificationRouteImport.update({
  id: '/account/notification',
  path: '/account/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagPageRoute = TagsTagPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => TagsTagRoute,
} as any)
const PostSlugOgDotpngRoute = PostSlugOgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => PostSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/achieve': typeof AchieveRoute
  '/archive': typeof ArchiveRoute
  '/credits': typeof CreditsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/account/notification': typeof AccountNotificationRoute
  '/post/$slug': typeof PostSlugRouteWithChildren
  '/tags/$tag': typeof TagsTagRouteWithChildren
  '/post/': typeof PostIndexRoute
  '/post/$slug/og.png': typeof PostSlugOgDotpngRoute
  '/tags/$tag/$page': typeof TagsTagPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/achieve': typeof AchieveRoute
  '/archive': typeof ArchiveRoute
  '/credits': typeof CreditsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/account/notification': typeof AccountNotificationRoute
  '/post/$slug': typeof PostSlugRouteWithChildren
  '/tags/$tag': typeof TagsTagRouteWithChildren
  '/post': typeof PostIndexRoute
  '/post/$slug/og.png': typeof PostSlugOgDotpngRoute
  '/tags/$tag/$page': typeof TagsTagPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/achieve': typeof AchieveRoute
  '/archive': typeof ArchiveRoute
  '/credits': typeof CreditsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-0.xml': typeof Sitemap0DotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/account/notification': typeof AccountNotificationRoute
  '/post/$slug': typeof PostSlugRouteWithChildren
  '/tags/$tag': typeof TagsTagRouteWithChildren
  '/post/': typeof PostIndexRoute
  '/post/$slug/og.png': typeof PostSlugOgDotpngRoute
  '/tags/$tag/$page': typeof TagsTagPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/404'
    | '/about'
    | '/achieve'
    | '/archive'
    | '/credits'
    | '/feed.xml'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/account/notification'
    | '/post/$slug'
    | '/tags/$tag'
    | '/post/'
    | '/post/$slug/og.png'
    | '/tags/$tag/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/404'
    | '/about'
    | '/achieve'
    | '/archive'
    | '/credits'
    | '/feed.xml'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/account/notification'
    | '/post/$slug'
    | '/tags/$tag'
    | '/post'
    | '/post/$slug/og.png'
    | '/tags/$tag/$page'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/404'
    | '/about'
    | '/achieve'
    | '/archive'
    | '/credits'
    | '/feed.xml'
    | '/robots.txt'
    | '/sitemap-0.xml'
    | '/sitemap-index.xml'
    | '/account/notification'
    | '/post/$slug'
    | '/tags/$tag'
    | '/post/'
    | '/post/$slug/og.png'
    | '/tags/$tag/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AchieveRoute: typeof AchieveRoute
  ArchiveRoute: typeof ArchiveRoute
  CreditsRoute: typeof CreditsRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  Sitemap0DotxmlRoute: typeof Sitemap0DotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  AccountNotificationRoute: typeof AccountNotificationRoute
  PostSlugRoute: typeof PostSlugRouteWithChildren
  TagsTagRoute: typeof TagsTagRouteWithChildren
  PostIndexRoute: typeof PostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-0.xml': {
      id: '/sitemap-0.xml'
      path: '/sitemap-0.xml'
      fullPath: '/sitemap-0.xml'
      preLoaderRoute: typeof Sitemap0DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achieve': {
      id: '/achieve'
      path: '/achieve'
      fullPath: '/achieve'
      preLoaderRoute: typeof AchieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notification': {
      id: '/account/notification'
      path: '/account/notification'
      fullPath: '/account/notification'
      preLoaderRoute: typeof AccountNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag/$page': {
      id: '/tags/$tag/$page'
      path: '/$page'
      fullPath: '/tags/$tag/$page'
      preLoaderRoute: typeof TagsTagPageRouteImport
      parentRoute: typeof TagsTagRoute
    }
    '/post/$slug/og.png': {
      id: '/post/$slug/og.png'
      path: '/og.png'
      fullPath: '/post/$slug/og.png'
      preLoaderRoute: typeof PostSlugOgDotpngRouteImport
      parentRoute: typeof PostSlugRoute
    }
  }
}

interface PostSlugRouteChildren {
  PostSlugOgDotpngRoute: typeof PostSlugOgDotpngRoute
}

const PostSlugRouteChildren: PostSlugRouteChildren = {
  PostSlugOgDotpngRoute: PostSlugOgDotpngRoute,
}

const PostSlugRouteWithChildren = PostSlugRoute._addFileChildren(
  PostSlugRouteChildren,
)

interface TagsTagRouteChildren {
  TagsTagPageRoute: typeof TagsTagPageRoute
}

const TagsTagRouteChildren: TagsTagRouteChildren = {
  TagsTagPageRoute: TagsTagPageRoute,
}

const TagsTagRouteWithChildren =
  TagsTagRoute._addFileChildren(TagsTagRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AchieveRoute: AchieveRoute,
  ArchiveRoute: ArchiveRoute,
  CreditsRoute: CreditsRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  Sitemap0DotxmlRoute: Sitemap0DotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  AccountNotificationRoute: AccountNotificationRoute,
  PostSlugRoute: PostSlugRouteWithChildren,
  TagsTagRoute: TagsTagRouteWithChildren,
  PostIndexRoute: PostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
